### ISSUE TITLE
CRON alignment with HDX Signals

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/hdx-scraper-idmc-idu#1]
For HDX Signals, we are checking to ensure that we have aligned CRON jobs across the datasets we use. We have aligned our food security updates based on something Godfrey noticed, see [this PR](https://github.com/OCHA-DAP/hdx-signals/pull/116). 

However, I wanted to check about the logic behind the 19:45 UTC scheduling for this scraper to see if there is a risk of misalignment between HDX Signals and HDX data if we run at 08:00 UTC. Obviously there might be misalignment if we expect updates to the IDMC IDU between those times, but seems relatively unlikely given the IDU is managed out of Geneva.

**Comment by mcarans** [comment]
@caldwellst The timing I have set is arbitrary and I can change it to whatever works for Signals. Please let me know what would work best.

**Comment by caldwellst** [comment]
Thanks @mcarans. Could we move to 08:10 UTC like done [here](https://github.com/OCHA-DAP/hdx-scraper-ipc/blob/0267f52f9728f7ac7315cf903a34261ee738b2bd/.github/workflows/run-python-script.yml#L8) please? That way we can be confident we will have downloaded and processed our data prior to your run.

**Comment by mcarans** [comment]
Done. Please close if all good.
